// web/src/lib/ui/Avatar.svelte
<!-- https://github.com/vercel/avatar/blob/master/utils/gradient.ts -->

<script lang="ts" module>
	import color from 'tinycolor2';

	function djb2(str: string): number {
		let hash = 5381;
		for (let i = 0; i < str.length; i++) {
			hash = (hash << 5) + hash + str.charCodeAt(i);
		}
		return hash;
	}

	type Gradient = { fromColor: string; toColor: string };

	const avatarGradientCache: { [username: string]: Gradient } = {};

	export function generateGradient(username: string): Gradient {
		if (avatarGradientCache[username]) return avatarGradientCache[username];

		const first = color({ h: djb2(username) % 360, s: 0.95, l: 0.5 });
		const second = first.triad()[1];

		return (avatarGradientCache[username] = {
			fromColor: first.toHexString(),
			toColor: second.toHexString()
		});
	}
</script>

<script lang="ts">
	import type { SvelteHTMLElements } from 'svelte/elements';
	import { keepAlphanumeric } from '$lib/utils';

	let {
		size = 'md',
		username,
		avatarUrl,
		class: className,
		...rest
	}: {
		size?: 'sm' | 'md' | 'lg';
		username: string;
		avatarUrl?: string;
	} & SvelteHTMLElements['img'] &
		SvelteHTMLElements['svg'] = $props();

	const containerClass = () => [
		'rounded-full',
		size === 'sm' ? 'size-10' : size === 'md' ? 'size-24' : 'size-36',
		className
	];
</script>

{#if avatarUrl}
	<img src={avatarUrl} alt={username} width="120" height="120" class={containerClass()} {...rest} />
{:else}
	{@const { fromColor, toColor } = generateGradient(username)}
	<svg
		width="120"
		height="120"
		viewBox="0 0 120 120"
		version="1.1"
		xmlns="http://www.w3.org/2000/svg"
		class={containerClass()}
		{...rest}
	>
		<g>
			<defs>
				<linearGradient id={keepAlphanumeric(username)} x1="0" y1="0" x2="1" y2="1">
					<stop offset="0%" stop-color={fromColor} />
					<stop offset="100%" stop-color={toColor} />
				</linearGradient>
			</defs>
			<rect fill={`url(#${keepAlphanumeric(username)})`} x="0" y="0" width="120" height="120" />
		</g>
	</svg>
{/if}

// client/src/lib/components/ui/Avatar.tsx
import { ComponentProps } from "solid-js";
import { tv, VariantProps } from "tailwind-variants";
import { generateGradient } from "~/lib/avatar";
import { removeNonAlphanumeric } from "~/lib/utils";

const avatar = tv({
  base: "rounded-full",
});

type AvatarProps = ComponentProps<"img"> &
  ComponentProps<"svg"> &
  VariantProps<typeof avatar> & {
    username: string;
    url?: string;
    size: number;
  };

export function Avatar(props: AvatarProps) {
  props.class = avatar(props);
  const filteredUsername = removeNonAlphanumeric(props.username);

  if (!props.url) {
    const { fromColor, toColor } = generateGradient(props.username);

    return (
      <svg
        width={props.size}
        height={props.size}
        viewBox={`0 0 ${props.size} ${props.size}`}
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <g>
          <defs>
            <linearGradient id={filteredUsername} x1="0" y1="0" x2="1" y2="1">
              <stop offset="0%" stop-color={fromColor} />
              <stop offset="100%" stop-color={toColor} />
            </linearGradient>
          </defs>
          <rect
            fill={`url(#${filteredUsername})`}
            x="0"
            y="0"
            width={props.size}
            height={props.size}
          />
        </g>
      </svg>
    );
  }

  return (
    <img
      src={props.url}
      alt="profile picture"
      title={props.username}
      width={props.size}
      height={props.size}
      {...props}
    />
  );
}
