// web/src/lib/ui/Button.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from 'svelte/elements';

	type Props = {
		color: 'pastel-blue' | 'pastel-pink';
	};

	const { children, color, ...rest }: HTMLButtonAttributes & Props = $props();
</script>

<button
	{...rest}
	class={[
		'border bg-dark-dark-green p-4 text-xl transition-all active:translate-y-1.5 active:text-dark-dark-green disabled:pointer-events-none disabled:opacity-50',
		color === 'pastel-blue'
			? `border-pastel-blue text-pastel-blue active:bg-pastel-blue`
			: `border-pastel-pink text-pastel-pink active:bg-pastel-pink`,
		rest.class
	]}
>
	{@render children?.()}
</button>

// client/src/lib/components/ui/Button.tsx
import { ComponentProps } from "solid-js";
import { tv, VariantProps } from "tailwind-variants";

const button = tv({
  base: "rounded-lg border transition-opacity active:opacity-75 disabled:opacity-50",
  variants: {
    color: {
      primary: "bg-dark-green text-foreground",
      secondary: "bg-blue text-foreground",
      muted: "bg-light-background text-light-green",
    },
    size: {
      sm: "px-2 py-1.5",
      md: "px-2.5 py-2.5",
      lg: "px-3 py-4 font-medium",
    },
  },
  defaultVariants: {
    color: "primary",
    size: "md",
  },
});

type ButtonProps = ComponentProps<"button"> & VariantProps<typeof button>;

export function Button(props: ButtonProps) {
  props.class = button(props);

  return <button {...props} />;
}
