// client/src/lib/components/Chat.tsx
import { Accessor, createEffect, For, on, onCleanup, onMount } from "solid-js";
import { Input } from "~/lib/components/ui/Input";
import { ChatMessage, ChatMessageType, Room, SendFn } from "~/lib/types/game";
import { generateGradient } from "../avatar";
import { getUsername } from "../utils";

const avatarColorCache: { [username: string]: [from: string, to: string] } = {};

export function Chat({
  sendMsg,
  room,
  messages,
}: {
  sendMsg: SendFn;
  room: Accessor<Room>;
  messages: Accessor<Array<ChatMessage>>;
}) {
  let chatElement!: HTMLDivElement;
  let chatContentElement!: HTMLUListElement;
  let chatInputElement!: HTMLInputElement;

  let animations: Array<Animation> = [];
  let fadeOutTimeout: ReturnType<typeof setTimeout> | undefined;

  function startFadeOut(duration = 3500) {
    clearTimeout(fadeOutTimeout);

    if (chatContentElement.matches(":hover") || document.activeElement == chatInputElement) {
      return;
    }

    const options = {
      easing: "ease-out",
      duration,
      fill: "forwards",
    } as const;

    animations.push(chatElement.animate({ borderColor: "transparent" }, options));
    animations.push(chatContentElement.animate({ opacity: "0%" }, options));
  }

  function reappear() {
    animations.forEach((animation) => animation.cancel());
    animations = [];
  }

  createEffect(
    on(
      () => messages().length,
      () => {
        reappear();
        chatContentElement.scrollTop = chatContentElement.scrollHeight;
        setTimeout(startFadeOut, 1500);
      },
    ),
  );

  onMount(() => {
    startFadeOut(5000);
  });

  const controller = new AbortController();

  document.addEventListener(
    "keydown",
    (event) => {
      if (document.activeElement?.tagName === "INPUT") return;

      if (event.key === "t") {
        chatInputElement.focus();
        event.preventDefault();
      }
    },
    { signal: controller.signal },
  );

  onCleanup(() => controller.abort());

  return (
    <div
      ref={chatElement}
      class="fixed bottom-0 left-0 z-10 flex w-96 flex-col gap-y-2 rounded-tr-lg border-r border-t bg-transparent p-2"
      onMouseEnter={reappear}
      onMouseLeave={() => startFadeOut()}
    >
      <ul
        ref={chatContentElement}
        class="list-item h-48 overflow-y-auto overflow-x-hidden text-wrap"
      >
        <li class="text-green">server: welcome to wordplay beta</li>
        <li class="text-green">
          server: leave issues/feedback on{" "}
          <a href="https://github.com/skearya/wordplay" target="_blank" class="text-gray-200">
            github
          </a>
        </li>
        <li class="text-green">
          server: use <kbd class="small-key">t</kbd> to open chat
        </li>
        <li class="text-green">
          server: and <kbd class="small-key">esc</kbd> to focus game input
        </li>
        <For each={messages()}>
          {(message) => {
            switch (message.type) {
              case ChatMessageType.Client:
                const username = getUsername(room(), message.uuid)!;

                let colors = avatarColorCache[username];
                if (!colors) {
                  const { fromColor, toColor } = generateGradient(username);
                  colors = [fromColor, toColor];
                  avatarColorCache[username] = colors;
                }

                return (
                  <li>
                    <span
                      style={{
                        "background-image": `linear-gradient(45deg, ${colors[0]}, ${colors[1]})`,
                      }}
                      class="bg-clip-text text-transparent"
                    >
                      {username}:
                    </span>{" "}
                    {message.content}
                  </li>
                );
              case ChatMessageType.Info:
                return <li class="text-green">{`server: ${message.content}`}</li>;
              case ChatMessageType.Error:
                return <li class="text-red-400">{`error: ${message.content}`}</li>;
            }
          }}
        </For>
      </ul>
      <Input
        ref={chatInputElement}
        size="sm"
        class="bg-transparent"
        maxLength={250}
        placeholder="send a message..."
        onEnter={(input) => {
          if (input.value.length !== 0) {
            sendMsg({ type: "ChatMessage", content: input.value });
            input.value = "";
          }
        }}
        onFocus={reappear}
        onBlur={() => startFadeOut()}
      />
    </div>
  );
}

// web/src/lib/components/lobby/Chat.svelte
<script lang="ts" module>
	type Message = { key: string; author: string; content: string };

	let messages: Message[] = $state([]);
</script>

<script lang="ts">
	import type { Props } from '$lib/context';
	import type { TransitionConfig } from 'svelte/transition';
	import { onMount } from 'svelte';
	import { cubicOut } from 'svelte/easing';
	import Avatar from '$lib/components/Avatar.svelte';
	import { generalEmitter } from '$lib/events';
	import Me from '$lib/icons/Me.svelte';
	import Tag from '$lib/ui/Tag.svelte';

	let { ctx = $bindable(), sendMsg }: Omit<Props<never>, 'state'> = $props();

	let messagesContainer: HTMLElement;

	onMount(() =>
		generalEmitter.handle({
			chat: ({ author, content }) => {
				messages.push({ key: crypto.randomUUID(), author, content });
			},
			error: ({ message }) => {
				messages.push({ key: crypto.randomUUID(), author: 'Server', content: message });
			}
		})
	);

	$effect(() => {
		messages.length;

		messagesContainer.scrollTo({
			top: messagesContainer.scrollHeight,
			behavior: 'smooth'
		});
	});

	function messageIn(_node: HTMLElement): TransitionConfig {
		const delay = 0;
		const duration = 400;
		const easing = cubicOut;

		return {
			delay,
			duration,
			easing,
			css: (t) =>
				`background-color: color-mix(in srgb, var(--color-pastel-pink) ${50 - t * 50}%, transparent);`
		};
	}
</script>

<div class="relative flex h-full flex-col border border-pastel-pink bg-pastel-pink/10">
	<Tag class="bg-pastel-pink">Chat</Tag>
	<div bind:this={messagesContainer} class="flex-1 overflow-x-hidden overflow-y-auto pb-1">
		<div
			style="--stripe-color: var(--color-pastel-pink);"
			class="striped h-16 w-full border-b border-pastel-pink opacity-25"
		></div>
		{#each ['Welcome to Wordplay!', 'Please leave issues or feedback on <a href="https://github.com/skearya/wordplay" target="_blank" class="text-gray-200 underline">GitHub</a>.'] as content, i}
			{#await new Promise((resolve) => setTimeout(resolve, 500 + 2000 * i)) then}
				{@render messageSnippet({ key: `${i}`, author: 'Server', content }, true)}
			{/await}
		{/each}
		{#each messages as message (message.key)}
			{@render messageSnippet(message, false)}
		{/each}
	</div>
	<input
		maxlength="250"
		placeholder="Send a message..."
		class="border-t border-pink/25 px-3.5 py-3 transition-colors duration-75 focus:border-pink focus:ring-0 focus:outline-none disabled:opacity-50"
		onkeyup={(e) => {
			if (e.key === 'Enter' && e.currentTarget.value != '') {
				sendMsg({
					kind: 'general',
					data: { kind: 'chat', content: e.currentTarget.value }
				});

				e.currentTarget.value = '';
			}
		}}
	/>
</div>

{#snippet messageSnippet({ author, content }: Message, trusted: boolean)}
	<div in:messageIn class="flex items-center gap-2 px-2 py-1.5">
		{#if author === 'Server'}
			<Me width={147 * 0.275} height={152 * 0.275} class="flex-none" />
		{:else}
			<Avatar {ctx} uuid={author} size="sm" class="flex-none" />
		{/if}
		<div class="text-sm leading-snug">
			<p class="font-medium">{author === 'Server' ? author : ctx.clients[author].username}</p>
			{#if trusted}{@html content}{:else}{content}{/if}
		</div>
	</div>
{/snippet}
