// web/src/lib/components/Lobby.svelte
<script lang="ts">
	import type { LobbyState } from '@bindings/LobbyState';
	import type { TimerAction } from '@bindings/TimerAction';
	import type { Props } from '$lib/context';
	import { onMount } from 'svelte';
	import { fly } from 'svelte/transition';
	import grid2Svg from '$lib/assets/grid2.svg';
	import { lobbyEmitter } from '$lib/events';
	import Crown from '$lib/icons/Crown.svelte';
	import DoubleRightArrow from '$lib/icons/DoubleRightArrow.svelte';
	import DownArrow from '$lib/icons/DownArrow.svelte';
	import WordBomb from '$lib/icons/WordBomb.svelte';
	import Button from '$lib/ui/Button.svelte';

	const { ctx, initial, sendMsg }: Props<LobbyState> = $props();

	let lobby = $state(initial);

	const handleTimer = (action: TimerAction) => {
		switch (action) {
			case 'start':
				lobby.timerStart = BigInt(Date.now());
				break;
			case 'stop':
				lobby.timerStart = null;
				break;
			case 'none':
				break;
		}
	};

	onMount(() =>
		lobbyEmitter.handle({
			ready: ({ uuid, timer }) => {
				handleTimer(timer);

				lobby.ready.push(uuid);
			},
			unready: ({ uuid, timer }) => {
				handleTimer(timer);

				const index = lobby.ready.indexOf(uuid);
				if (index !== -1) lobby.ready.splice(index, 1);
			},
			practice: () => {},
			practiceResult: () => {}
		})
	);
</script>

<div class="flex flex-1 items-stretch gap-4 overflow-y-hidden p-4 pt-0">
	{#if lobby.prevGame}
		<section class="border-pink bg-pink/15 flex flex-[30%] flex-col overflow-y-hidden border">
			<div
				style={`background: url("${grid2Svg}"), #F3ACFF;`}
				class="background-scroll p-4 pt-16 text-black"
			>
				<div class="relative mb-2.5 size-20">
					<img
						src="https://avatar.vercel.sh/s"
						alt="avatar"
						width="120"
						height="120"
						class="h-full w-full rounded-full"
					/>
					<Crown class="absolute -right-4 -top-4" />
				</div>
				<h1 class="text-xl"><b>skeary</b> won the game!</h1>
			</div>
			<div class="flex flex-1 flex-col overflow-y-hidden p-4">
				<div class="mb-4 flex items-center justify-between gap-x-8 px-8">
					<div class="text-center">
						<h1 class="text-yellow font-serif text-4xl">21</h1>
						<p>Minutes Elapsed</p>
					</div>
					<div class="bg-pastel-pink w-[1px] rotate-12 self-stretch"></div>
					<div class="text-center">
						<h1 class="text-yellow font-serif text-4xl">21</h1>
						<p>Words Used</p>
					</div>
				</div>
				<div class="flex flex-1 flex-col overflow-y-hidden">
					<div class="flex items-center -space-x-1 text-nowrap">
						{#each ['Fastest Guess', 'Longest Word', 'Word Length', 'WPM'] as text, i}
							<button
								style={`z-index: ${4 - i};`}
								class={[
									i === 0
										? 'border-pastel-pink bg-pastel-pink text-black'
										: 'border-pink bg-[#2B212C]',
									'rounded-t-xl border border-b-0 px-2.5 py-1 text-sm'
								]}
							>
								{text}
							</button>
						{/each}
					</div>
					<div
						style="scrollbar-width: none;"
						class="border-pastel-pink flex-1 divide-y overflow-y-auto border"
					>
						{#each { length: 99 }, i}
							<div class="border-pastel-pink relative flex items-center space-x-2.5 p-2.5">
								<div
									class="bg-pastel-pink absolute left-0 top-0 content-center px-1 py-0.5 text-center text-xs text-black"
								>
									<p>{i + 1}</p>
								</div>
								<img
									src="https://avatar.vercel.sh/s"
									alt="avatar"
									width="120"
									height="120"
									class="size-12 rounded-full"
								/>
								<p>skeary</p>
								<p class="ml-auto">999ms</p>
							</div>
						{/each}
					</div>
				</div>
			</div>
		</section>
	{/if}
	<section class="border-green bg-green/15 relative flex flex-[70%] flex-col overflow-clip border">
		<div class="pointer-events-none absolute -bottom-6 -right-6 opacity-50">
			<WordBomb class="aspect-[901/916] w-[calc(min(45vw,60vh))] mix-blend-color-dodge" />
		</div>
		<div class="bg-green absolute left-0 top-0 w-min text-nowrap rounded-br-2xl px-3 py-1">
			<p>Ready Players</p>
		</div>
		<div class="text-bright-green absolute right-3 top-3 w-min text-nowrap">
			<p>{ctx.settings.size - lobby.ready.length} slots left</p>
		</div>
		<div class="flex flex-1 items-center justify-center gap-x-20 px-12">
			<div class="relative size-[304px]">
				<div
					class={[
						'absolute left-1/2 top-1/2 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center gap-y-4 text-[#B1C1AE] transition-opacity',
						lobby.ready.length === 0 ? 'delay-400 opacity-100' : 'opacity-0'
					]}
				>
					<div
						class="striped aspect-square size-24 content-center rounded-full border border-dashed text-center"
					>
						?
					</div>
					<p class="loading animate-pulse text-nowrap">Waiting for someone to ready</p>
				</div>
				{#each lobby.ready as uuid, i (uuid)}
					{@const angleBetween = (2 * Math.PI) / lobby.ready.length}
					{@const angle = i * angleBetween + Math.PI / 2}
					{@const distanceFromCenter = 80 + Math.log2(lobby.ready.length) * 20}
					{@const x = Math.cos(angle) * distanceFromCenter}
					{@const y = Math.sin(angle) * distanceFromCenter - 32}
					<div
						in:fly={{ x: 48, y: 48, duration: 400, delay: 150 }}
						out:fly={{ x: 48, y: -48, duration: 400 }}
						style={lobby.ready.length === 1
							? `translate: -50% -50%;`
							: `translate: calc(-50% + ${x}px) calc(-50% + ${-y}px); scale: ${100 - Math.log2(lobby.ready.length) * 8}%;`}
						class="timing-function-0 absolute left-1/2 top-1/2 flex flex-col items-center gap-y-2 transition-transform duration-[400ms]"
					>
						<img
							src={`https://avatar.vercel.sh/${ctx.clients[uuid]!.username}`}
							alt="avatar"
							width="120"
							height="120"
							class="size-24 rounded-full"
						/>
						<p>{ctx.clients[uuid]!.username}</p>
					</div>
				{/each}
			</div>
			<DoubleRightArrow />
			<button
				style="border-image: linear-gradient(to right, #475D50, #95C3A8) 1;"
				class="z-10 w-72 space-y-2.5 border p-4 pt-5 backdrop-blur-sm backdrop-brightness-90 transition-all"
			>
				<div class="flex items-center justify-between">
					<h1 class="text-yellow font-serif text-4xl">Word Bomb</h1>
					<DownArrow />
				</div>
				<div class="bg-green h-[1px] w-full"></div>
				<div class="text-light-green grid grid-cols-2 justify-between text-sm">
					<p class="text-left font-medium">Difficulty</p>
					<p class="text-right">Easy</p>
					<p class="text-left font-medium">Starting Lives</p>
					<p class="text-right">2</p>
				</div>
			</button>
		</div>
		<div class="z-10 flex gap-x-4 p-4">
			<Button
				color="pastel-pink"
				onclick={() => {
					sendMsg({
						kind: 'lobby',
						data: { kind: lobby.ready.includes(ctx.uuid) ? 'unready' : 'ready' }
					});
				}}
			>
				{lobby.ready.includes(ctx.uuid) ? 'Unready' : 'Ready'}
			</Button>
			<Button
				color="pastel-blue"
				disabled={ctx.settings.owner !== ctx.uuid || lobby.timerStart === null}
				onclick={() => {
					sendMsg({ kind: 'lobby', data: { kind: 'startEarly' } });
				}}
			>
				Start Early
			</Button>
		</div>
	</section>
</div>

// client/src/lib/components/Lobby.tsx
import { Accessor, For, Show } from "solid-js";
import { SetStoreFunction } from "solid-js/store";
import { useEvents } from "~/lib/events";
import { Bomb } from "~/lib/icons";
import { LobbyState, Room, SendFn, State } from "~/lib/types/game";
import { PostGameInfo } from "~/lib/types/messages";

export function Lobby({
  sendMsg,
  room,
  state,
  setState,
  postGameInfo,
}: {
  sendMsg: SendFn;
  room: Accessor<Room>;
  state: Accessor<State>;
  setState: SetStoreFunction<State>;
  postGameInfo: PostGameInfo | undefined;
}) {
  const [lobby, setLobby] = [
    state as Accessor<LobbyState>,
    setState as SetStoreFunction<LobbyState>,
  ];

  useEvents({
    ReadyPlayers: (data) => {
      setLobby("ready", data.ready);
    },
    StartingCountdown: (data) => {},
    GameStarted: (data) => {},
  });

  return (
    <main class="flex h-screen items-center justify-center overflow-hidden">
      <div class="z-10 flex h-[480px] gap-x-4 rounded-xl border bg-[#0B0D0A] p-3.5">
        <Show when={postGameInfo}>
          <div class="flex flex-col gap-y-3.5">
            <Winner />
            <div class="grid grid-cols-2 gap-x-10 gap-y-2.5 overflow-y-scroll">
              {["fastest guess", "longest word", "wpm", "word length"].map((title) => (
                <Leaderboard title={title} items={[]} />
              ))}
            </div>
            <Stats />
          </div>
          <div class="w-[1px] scale-y-90 self-stretch bg-[#475D50]/30"></div>
        </Show>
        <div class="flex w-[475px] flex-col gap-y-2">
          <ReadyPlayers room={room} lobby={lobby} />
          <JoinButtons sendMsg={sendMsg} room={room} lobby={lobby} />
        </div>
      </div>
      <Status />
      <Practice />
    </main>
  );
}

function Tabs() {
  return (
    <div class="flex overflow-hidden rounded-lg border text-center">
      <button class="flex-1 rounded-lg bg-[#475D50] py-2">Info</button>
      <button class="flex-1 rounded-lg py-2">Settings</button>
    </div>
  );
}

function Winner() {
  return (
    <div
      style="background-image: linear-gradient(135deg, #171717 6.52%, transparent 6.52%, transparent 50%, #171717 50%, #171717 56.52%, transparent 56.52%, transparent 100%); background-size: 23.00px 23.00px;"
      class="flex items-center justify-between rounded-lg border p-2.5"
    >
      <h1 class="text-lg font-medium">winner!</h1>
      <div class="flex items-center gap-x-4">
        <h1 class="text-lg">Player 1</h1>
        <img
          src="https://avatar.vercel.sh/skeary"
          alt="profile picture"
          width={50}
          height={50}
          class="rounded-full"
        />
      </div>
    </div>
  );
}

function Leaderboard({
  title,
  items,
}: {
  title: string;
  items: Array<{
    pfp: string;
    name: string;
    content: string;
  }>;
}) {
  return (
    <div>
      <h1 class="mb-1.5">{title}</h1>
      <div class="w-48 space-y-1.5">
        {items.map(({ pfp, name, content }, i) => (
          <div class="flex items-center gap-x-1">
            <h1 class="text-sm tabular-nums">{i + 1}.</h1>
            <img
              src={pfp}
              alt="profile picture"
              width={18}
              height={18}
              class="flex-none rounded-full"
            />
            <h1 class="flex-1 overflow-hidden text-ellipsis whitespace-nowrap text-sm">{name}</h1>
            <h1 class="justify-self-end text-sm text-[#8BA698]">{content}</h1>
          </div>
        ))}
      </div>
    </div>
  );
}

function Stats() {
  return (
    <div class="mt-auto text-center [&>h1>span]:text-[#62E297]">
      <h1 class="flex-1 border-[#62E297]">
        <span>21</span> mins elapsed
      </h1>
      <h1 class="flex-1 border-[#62E297]">
        <span>209</span> words used
      </h1>
      <h1 class="flex-1">
        <span>2032</span> letters typed
      </h1>
    </div>
  );
}

function ReadyPlayers({ room, lobby }: { room: Accessor<Room>; lobby: Accessor<LobbyState> }) {
  return (
    <>
      <div class="flex items-baseline justify-between">
        <h1 class="text-xl">Ready Players</h1>
        <h1 class="text-lg text-[#26D16C]">{100 - lobby().ready.length} slots left</h1>
      </div>
      <div class="grid grid-cols-2 gap-2.5 overflow-y-scroll">
        <For each={lobby().ready}>
          {(uuid) => {
            const username = room().clients.find((client) => client.uuid === uuid)!.username;

            return (
              <div class="flex items-center justify-between gap-x-4 rounded-lg border bg-[#475D50]/30 p-2">
                <img
                  src={`https://avatar.vercel.sh/${username}`}
                  alt={`profile picture`}
                  height={55}
                  width={55}
                  class="rounded-full"
                />
                <h1 class="overflow-hidden text-ellipsis whitespace-nowrap text-lg">{username}</h1>
              </div>
            );
          }}
        </For>
      </div>
    </>
  );
}

function JoinButtons({
  sendMsg,
  room,
  lobby,
}: {
  sendMsg: SendFn;
  room: Accessor<Room>;
  lobby: Accessor<LobbyState>;
}) {
  const ready = () => (lobby().ready.includes(room().uuid) ? "Unready" : "Ready");

  return (
    <div class="mt-auto flex gap-x-2.5">
      <button
        class="flex-1 rounded-lg border bg-[#475D50] py-4 font-medium"
        onClick={() => sendMsg({ type: ready() })}
      >
        {ready()}
      </button>
      <Show when={room().owner === room().uuid}>
        <button
          class="flex-1 rounded-lg border bg-[#345C8A] py-4 font-medium transition-all disabled:opacity-50"
          disabled={lobby().ready.length < 2}
          onClick={() => sendMsg({ type: "StartEarly" })}
        >
          Start Early
        </button>
      </Show>
    </div>
  );
}

function Practice() {
  return (
    <div class="absolute right-4 top-1/2 flex w-40 -translate-y-1/2 flex-col gap-y-3">
      <div class="flex items-center justify-between">
        <h3 class="text-[#8BA698]">practice</h3>
        <div
          style="background: linear-gradient(244.26deg, rgba(38, 209, 108, 0.5) 7.28%, rgba(76, 118, 93, 0.1) 82.41%);"
          class="rounded-lg px-2.5 py-0.5 font-mono text-lg"
        >
          UTS
        </div>
      </div>
      <div
        style="background: linear-gradient(to right, #26D16C 70%, transparent 30%)"
        class="h-[1px] w-full"
      ></div>
      <input type="text" placeholder="word" class="rounded-lg border bg-transparent px-2.5 py-2" />
    </div>
  );
}

function Status() {
  return (
    <div class="absolute bottom-0 right-0 flex flex-col items-end overflow-hidden">
      <div class="mr-3">
        <Bomb />
      </div>
      <h1 class="text-outline -skew-x-6 text-[4.5vw] leading-tight text-[#050705]">
        waiting for players...
      </h1>
    </div>
  );
}
