// client/src/lib/components/ui/Avatar.tsx
import { ComponentProps } from "solid-js";
import { tv, VariantProps } from "tailwind-variants";

const avatar = tv({
  base: "rounded-full",
});

type AvatarProps = ComponentProps<"img"> &
  VariantProps<typeof avatar> & {
    username: string;
    url?: string;
    size: number;
  };

export function Avatar(props: AvatarProps) {
  props["class"] = avatar(props);

  return (
    <img
      src={props.url ?? `https://avatar.vercel.sh/${props.username}`}
      alt="profile picture"
      title={props.username}
      width={props.size}
      height={props.size}
      {...props}
    />
  );
}

// web/src/lib/components/Avatar.svelte
<script lang="ts">
	import type { Props } from '$lib/context';
	import type { HTMLImgAttributes } from 'svelte/elements';

	let {
		ctx,
		uuid,
		size = 'md',
		class: className,
		...rest
	}: Omit<Props<never>, 'state' | 'sendMsg'> & {
		uuid: string;
		size?: 'sm' | 'md' | 'lg';
	} & HTMLImgAttributes = $props();

	let user = $derived(ctx.clients[uuid]!);
</script>

<img
	src={user.avatarUrl ? user.avatarUrl : `https://avatar.vercel.sh/${user.username}`}
	alt={user.username}
	title={user.connected ? user.username : `${user.username} (disconnected)`}
	width="120"
	height="120"
	class={[
		size === 'sm' ? 'size-10' : size === 'md' ? 'size-24' : 'size-36',
		user.connected ? 'opacity-100' : 'animate-pulse',
		'rounded-full transition-opacity',
		className
	]}
	{...rest}
/>
