// client/src/game/components/Nav.tsx
import { LinkIcon, QuestionMarkIcon } from "@game/components/Icons";
import { Context } from "@game/context";
import type { ClientInfo } from "@game/types/messages";
import { For, useContext } from "solid-js";

export function Nav() {
  const context = useContext(Context);
  if (!context) throw new Error("Not called inside context provider?");
  const { connection } = context[0];

  return (
    <nav class="fixed top-0 flex w-full justify-between p-6">
      <a href="/" class="text-xl">
        wordplay
      </a>
      <div class="flex items-center gap-4">
        <ConnectedClients clients={connection.clients.filter((client) => !client.disconnected)} />
        <button onClick={async () => await navigator.clipboard.writeText(window.location.href)}>
          <LinkIcon />
        </button>
        <button onClick={() => alert("unimplemented")}>
          <QuestionMarkIcon />
        </button>
      </div>
    </nav>
  );
}

function ConnectedClients(props: { clients: ClientInfo[] }) {
  return (
    <div class="group relative flex items-center -space-x-2 pr-1">
      <For each={props.clients}>
        {(client) => (
          <img
            class="h-9 w-9 rounded-full border-2 border-black"
            src={`https://avatar.vercel.sh/${client.username}`}
            alt="avatar"
          />
        )}
      </For>
      <div class="absolute left-1/2 top-0 hidden -translate-x-1/2 translate-y-12 rounded-xl border bg-primary-50 p-2 group-hover:block">
        <div class="flex flex-col gap-y-2">
          <For each={props.clients}>
            {(client) => (
              <div class="flex min-w-40 items-center justify-between gap-2 rounded-lg border bg-primary-100 p-2">
                <h1>{client.username}</h1>
                <img
                  class="h-8 w-8 rounded-full"
                  src={`https://avatar.vercel.sh/${client.username}`}
                  alt="avatar"
                  title={client.uuid}
                />
              </div>
            )}
          </For>
        </div>
      </div>
    </div>
  );
}

// web/src/lib/components/Nav.svelte
<script lang="ts">
	import type { Props } from '$lib/context';
	import GreenSettings from '$lib/icons/GreenSettings.svelte';
	import Logo from '$lib/icons/Logo.svelte';

	const { ctx, sendMsg }: Omit<Props<never>, 'initial'> = $props();

	const navOnFocus = (nav: HTMLElement) => {
		if (ctx.state.kind === 'lobby') return;
		nav.classList.remove('opacity-0');
	};

	const navOnBlur = (nav: HTMLElement) => {
		if (ctx.state.kind === 'lobby') return;
		nav.classList.add('opacity-0');
	};
</script>

<nav
	class={[
		'flex items-center justify-between px-5 py-4',
		ctx.state.kind !== 'lobby'
			? 'bg-background/90 fixed left-0 top-0 z-40 w-full opacity-0 transition-opacity'
			: 'opacity-100'
	]}
	onmouseover={(e) => navOnFocus(e.currentTarget)}
	onfocus={(e) => navOnFocus(e.currentTarget)}
	onmouseout={(e) => navOnBlur(e.currentTarget)}
	onblur={(e) => navOnBlur(e.currentTarget)}
>
	<Logo />
	<div class="flex items-center gap-x-4">
		<div class="border-green flex -space-x-4">
			{#each Object.entries(ctx.clients).slice(0, 4) as [uuid, client]}
				<img
					src={`https://avatar.vercel.sh/${client!.username}`}
					alt={client!.username}
					title={`${client!.username} (${uuid})`}
					width="120"
					height="120"
					class="size-10 rounded-full border border-black"
				/>
			{/each}
			{#if Object.keys(ctx.clients).length > 4}
				<div class="border-green size-10 content-center rounded-full border bg-black text-center">
					+{Object.keys(ctx.clients).length - 4}
				</div>
			{/if}
		</div>
		<GreenSettings />
	</div>
</nav>
