// client/src/lib/components/Nav.tsx
import { Accessor, createSignal, onCleanup, Show } from "solid-js";
import { useEvent } from "~/lib/events";
import { Link, QuestionMark } from "~/lib/icons";
import { Room, SendFn } from "~/lib/types/game";

export function GameNav({ sendMsg, room }: { sendMsg: SendFn; room: Accessor<Room> }) {
  const [ping, setPing] = createSignal(0);

  const sendPing = () => sendMsg({ type: "Ping", timestamp: Date.now() });
  sendPing();

  const pingInterval = setInterval(sendPing, 10000);

  useEvent("Pong", (data) => setPing(Date.now() - data.timestamp));

  onCleanup(() => clearInterval(pingInterval));

  return (
    <nav class="absolute top-0 flex w-full items-center justify-between px-6 py-5">
      <h1 class="text-2xl">wordplay</h1>
      <div class="flex items-center gap-x-5">
        <div
          style="box-shadow: 0px 0px 15.5px 1px #26D16C"
          class="h-[13px] w-[13px] rounded-full bg-[#26D16C]"
        />
        <h1 class="text-[#B1C1AE]">{ping()}ms</h1>
        <div class="flex -space-x-2">
          {room()
            .clients.slice(0, 3)
            .map((client) => (
              <img
                src={`https://avatar.vercel.sh/${client.username}`}
                alt={client.username}
                title={client.username}
                height={38}
                width={38}
                class="rounded-full border-[3px] border-black"
              />
            ))}
          <Show when={room().clients.length > 3}>
            <div class="flex h-[38px] w-[38px] items-center justify-center rounded-full bg-black">
              <h1>+{room().clients.length - 3}</h1>
            </div>
          </Show>
        </div>
        <Link />
        <QuestionMark />
      </div>
    </nav>
  );
}

// web/src/lib/components/Nav.svelte
<script>
	import GreenSettings from '$lib/icons/GreenSettings.svelte';
	import Logo from '$lib/icons/Logo.svelte';
</script>

<nav class="flex items-center justify-between px-5 py-4">
	<Logo />
	<div class="flex items-center gap-x-4">
		<div class="flex -space-x-6">
			{#each { length: 3 }}
				<img
					src="https://avatar.vercel.sh/s"
					alt="avatar"
					width="120"
					height="120"
					class="size-12 rounded-full border-2 border-black"
				/>
			{/each}
			<div
				class="border-dark-green size-12 content-center rounded-full border-2 bg-black text-center"
			>
				+2
			</div>
		</div>
		<GreenSettings />
	</div>
</nav>
